/**
 * Copyright (c) 2012-2017 Marsha Chechik, Alessio Di Sandro, Michalis Famelis,
 * Rick Salay.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *    Alessio Di Sandro - Implementation.
 */
package edu.toronto.cs.se.mmint.mid.operator.provider;

import edu.toronto.cs.se.mmint.mid.operator.util.OperatorAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class OperatorItemProviderAdapterFactory extends OperatorAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public OperatorItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.toronto.cs.se.mmint.mid.operator.Operator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperatorItemProvider operatorItemProvider;

	/**
	 * This creates an adapter for a {@link edu.toronto.cs.se.mmint.mid.operator.Operator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperatorAdapter() {
		if (operatorItemProvider == null) {
			operatorItemProvider = new OperatorItemProvider(this);
		}

		return operatorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.toronto.cs.se.mmint.mid.operator.ConversionOperator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConversionOperatorItemProvider conversionOperatorItemProvider;

	/**
	 * This creates an adapter for a {@link edu.toronto.cs.se.mmint.mid.operator.ConversionOperator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConversionOperatorAdapter() {
		if (conversionOperatorItemProvider == null) {
			conversionOperatorItemProvider = new ConversionOperatorItemProvider(this);
		}

		return conversionOperatorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.toronto.cs.se.mmint.mid.operator.RandomOperator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RandomOperatorItemProvider randomOperatorItemProvider;

	/**
	 * This creates an adapter for a {@link edu.toronto.cs.se.mmint.mid.operator.RandomOperator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRandomOperatorAdapter() {
		if (randomOperatorItemProvider == null) {
			randomOperatorItemProvider = new RandomOperatorItemProvider(this);
		}

		return randomOperatorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.toronto.cs.se.mmint.mid.operator.NestingOperator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NestingOperatorItemProvider nestingOperatorItemProvider;

	/**
	 * This creates an adapter for a {@link edu.toronto.cs.se.mmint.mid.operator.NestingOperator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNestingOperatorAdapter() {
		if (nestingOperatorItemProvider == null) {
			nestingOperatorItemProvider = new NestingOperatorItemProvider(this);
		}

		return nestingOperatorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.toronto.cs.se.mmint.mid.operator.WorkflowOperator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WorkflowOperatorItemProvider workflowOperatorItemProvider;

	/**
	 * This creates an adapter for a {@link edu.toronto.cs.se.mmint.mid.operator.WorkflowOperator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWorkflowOperatorAdapter() {
		if (workflowOperatorItemProvider == null) {
			workflowOperatorItemProvider = new WorkflowOperatorItemProvider(this);
		}

		return workflowOperatorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.toronto.cs.se.mmint.mid.operator.GenericEndpoint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GenericEndpointItemProvider genericEndpointItemProvider;

	/**
	 * This creates an adapter for a {@link edu.toronto.cs.se.mmint.mid.operator.GenericEndpoint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGenericEndpointAdapter() {
		if (genericEndpointItemProvider == null) {
			genericEndpointItemProvider = new GenericEndpointItemProvider(this);
		}

		return genericEndpointItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.toronto.cs.se.mmint.mid.operator.OperatorInput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperatorInputItemProvider operatorInputItemProvider;

	/**
	 * This creates an adapter for a {@link edu.toronto.cs.se.mmint.mid.operator.OperatorInput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperatorInputAdapter() {
		if (operatorInputItemProvider == null) {
			operatorInputItemProvider = new OperatorInputItemProvider(this);
		}

		return operatorInputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.toronto.cs.se.mmint.mid.operator.OperatorGeneric} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperatorGenericItemProvider operatorGenericItemProvider;

	/**
	 * This creates an adapter for a {@link edu.toronto.cs.se.mmint.mid.operator.OperatorGeneric}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperatorGenericAdapter() {
		if (operatorGenericItemProvider == null) {
			operatorGenericItemProvider = new OperatorGenericItemProvider(this);
		}

		return operatorGenericItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.toronto.cs.se.mmint.mid.operator.OperatorConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperatorConstraintItemProvider operatorConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link edu.toronto.cs.se.mmint.mid.operator.OperatorConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperatorConstraintAdapter() {
		if (operatorConstraintItemProvider == null) {
			operatorConstraintItemProvider = new OperatorConstraintItemProvider(this);
		}

		return operatorConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.toronto.cs.se.mmint.mid.operator.OperatorConstraintRule} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperatorConstraintRuleItemProvider operatorConstraintRuleItemProvider;

	/**
	 * This creates an adapter for a {@link edu.toronto.cs.se.mmint.mid.operator.OperatorConstraintRule}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperatorConstraintRuleAdapter() {
		if (operatorConstraintRuleItemProvider == null) {
			operatorConstraintRuleItemProvider = new OperatorConstraintRuleItemProvider(this);
		}

		return operatorConstraintRuleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.toronto.cs.se.mmint.mid.operator.OperatorConstraintParameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperatorConstraintParameterItemProvider operatorConstraintParameterItemProvider;

	/**
	 * This creates an adapter for a {@link edu.toronto.cs.se.mmint.mid.operator.OperatorConstraintParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperatorConstraintParameterAdapter() {
		if (operatorConstraintParameterItemProvider == null) {
			operatorConstraintParameterItemProvider = new OperatorConstraintParameterItemProvider(this);
		}

		return operatorConstraintParameterItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (operatorItemProvider != null) operatorItemProvider.dispose();
		if (conversionOperatorItemProvider != null) conversionOperatorItemProvider.dispose();
		if (randomOperatorItemProvider != null) randomOperatorItemProvider.dispose();
		if (nestingOperatorItemProvider != null) nestingOperatorItemProvider.dispose();
		if (workflowOperatorItemProvider != null) workflowOperatorItemProvider.dispose();
		if (genericEndpointItemProvider != null) genericEndpointItemProvider.dispose();
		if (operatorInputItemProvider != null) operatorInputItemProvider.dispose();
		if (operatorGenericItemProvider != null) operatorGenericItemProvider.dispose();
		if (operatorConstraintItemProvider != null) operatorConstraintItemProvider.dispose();
		if (operatorConstraintRuleItemProvider != null) operatorConstraintRuleItemProvider.dispose();
		if (operatorConstraintParameterItemProvider != null) operatorConstraintParameterItemProvider.dispose();
	}

}
