<?xml version="1.0" encoding="ISO-8859-1"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="statemachine_mavo" nsURI="http://se.cs.toronto.edu/modelepedia/StateMachine_MAVO"
    nsPrefix="statemachine_mavo">
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine" eSuperTypes="../../edu.toronto.cs.se.mavo/model/mavo.ecore#//MAVORoot">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//AbstractState" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FiringElement" abstract="true" eSuperTypes="../../edu.toronto.cs.se.mavo/model/mavo.ecore#//MAVOElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trigger" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractState" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitionsAsSource" upperBound="-1"
        eType="#//Transition" eOpposite="#//Transition/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitionsAsTarget" upperBound="-1"
        eType="#//Transition" eOpposite="#//Transition/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="../../edu.toronto.cs.se.mavo/model/mavo.ecore#//MAVOElement #//AbstractState">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalActions" upperBound="-1"
        eType="#//StateAction" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="layout" value="list"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialState" eSuperTypes="#//AbstractState">
    <eAnnotations source="gmf.node">
      <details key="label.placement" value="none"/>
      <details key="figure" value="ellipse"/>
      <details key="size" value="20,20"/>
      <details key="color" value="0,0,0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FinalState" eSuperTypes="#//AbstractState">
    <eAnnotations source="gmf.node">
      <details key="label.placement" value="none"/>
      <details key="figure" value="rectangle"/>
      <details key="size" value="20,20"/>
      <details key="color" value="0,0,0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#//FiringElement">
    <eAnnotations source="gmf.link">
      <details key="label" value="trigger,action"/>
      <details key="label.pattern" value="{0}/{1}"/>
      <details key="label.icon" value="true"/>
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="target.decoration" value="arrow"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//AbstractState" eOpposite="#//AbstractState/transitionsAsSource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//AbstractState" eOpposite="#//AbstractState/transitionsAsTarget"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateAction" eSuperTypes="#//FiringElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="trigger,action"/>
      <details key="label.pattern" value="{0}/{1}"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
