<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="safetycase" nsURI="http://se.cs.toronto.edu/modelepedia/SafetyCase"
    nsPrefix="safetycase">
  <eClassifiers xsi:type="ecore:EClass" name="SafetyCase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="goals" upperBound="-1"
        eType="#//Goal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="strategies" upperBound="-1"
        eType="#//Strategy" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="solutions" upperBound="-1"
        eType="#//Solution" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contexts" upperBound="-1"
        eType="#//Context" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="justifications" upperBound="-1"
        eType="#//Justification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArgumentElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="gmf.label">
        <details key="label" value="description"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentValidity" eType="#//ContentValidity"
        containment="true" eOpposite="#//ContentValidity/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatefulElement" abstract="true" eSuperTypes="#//ArgumentElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateValidity" eType="#//StateValidity"
        containment="true" eOpposite="#//StateValidity/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreElement" abstract="true" eSuperTypes="#//ArgumentElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="supports" upperBound="-1"
        eType="#//SupportedBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DecomposableCoreElement" abstract="true"
      eSuperTypes="#//CoreElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inContextOf" upperBound="-1"
        eType="#//InContextOf" containment="true" eOpposite="#//InContextOf/contextOf"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextualElement" abstract="true" eSuperTypes="#//ArgumentElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextOf" lowerBound="1"
        upperBound="-1" eType="#//InContextOf" eOpposite="#//InContextOf/context"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SupportedBy" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SupportedByDecomposable" eSuperTypes="#//SupportedBy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="premise" lowerBound="1"
        eType="#//DecomposableCoreElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SupportedByCore" eSuperTypes="#//SupportedBy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="premise" lowerBound="1"
        eType="#//CoreElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InContextOf">
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
        eType="#//ContextualElement" eOpposite="#//ContextualElement/contextOf"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextOf" lowerBound="1"
        eType="#//DecomposableCoreElement" eOpposite="#//DecomposableCoreElement/inContextOf"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Goal" eSuperTypes="#//DecomposableCoreElement #//StatefulElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedBy" upperBound="-1"
        eType="#//SupportedByDecomposable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="asil" eType="#//ASIL" containment="true"
        eOpposite="#//ASIL/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Strategy" abstract="true" eSuperTypes="#//DecomposableCoreElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BasicStrategy" eSuperTypes="#//Strategy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedBy" upperBound="-1"
        eType="#//SupportedByCore" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASILDecompositionStrategy" eSuperTypes="#//Strategy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedBy" lowerBound="2"
        upperBound="2" eType="#//SupportedByDecomposable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedByIndependent"
        lowerBound="1" eType="#//SupportedByDecomposable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Solution" eSuperTypes="#//CoreElement #//StatefulElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Context" eSuperTypes="#//ContextualElement"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ASILLevel">
    <eLiterals name="D" literal="D"/>
    <eLiterals name="C" value="1" literal="C"/>
    <eLiterals name="B" value="2" literal="B"/>
    <eLiterals name="A" value="3" literal="A"/>
    <eLiterals name="QM" value="4" literal="QM"/>
    <eLiterals name="None" value="5" literal="None"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ValidityValue">
    <eLiterals name="Invalid" literal="Invalid"/>
    <eLiterals name="Valid" value="1" literal="Valid"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ImpactType">
    <eLiterals name="Revise" value="1"/>
    <eLiterals name="Recheck" value="2" literal="Recheck"/>
    <eLiterals name="Reuse" value="3" literal="Reuse"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImpactAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//ImpactType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Justification" eSuperTypes="#//ContextualElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Impactable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="status" eType="#//ImpactAnnotation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementValidity" eSuperTypes="#//Impactable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="#//ValidityValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentValidity" eSuperTypes="#//ElementValidity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//ArgumentElement" eOpposite="#//ArgumentElement/contentValidity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateValidity" eSuperTypes="#//ElementValidity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//StatefulElement" eOpposite="#//StatefulElement/stateValidity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASIL" eSuperTypes="#//Impactable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="#//ASILLevel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Goal" eOpposite="#//Goal/asil"/>
  </eClassifiers>
</ecore:EPackage>
