<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mavo" nsURI="http://se.cs.toronto.edu/MAVO" nsPrefix="mavo">
  <eClassifiers xsi:type="ecore:EClass" name="LogicElement" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The abstract element of a logic formula, i.e. an element that can be represented by a variable in a logic formula."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formulaVariable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The variable in the logic formula that corresponds to this logic element."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DecisionElement" abstract="true" eSuperTypes="#//LogicElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The abstract element of a decision, i.e. an element that can have a description to specify the rationale for the decision."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The description of the rationale for this decision element."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAVOModel" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The abstract MAVO model. It represents a model that can have MAVO open world annotations."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="True if this model is incomplete (INC), false if it is complete (COMP)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decisions" upperBound="-1"
        eType="#//MAVODecision" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The list of decisions to be made within this MAVO model."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAVOElement" abstract="true" eSuperTypes="#//LogicElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The abstract MAVO element. It represents an element that can have MAVO partiality annotations."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="may" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="True if this element may exist (M), false if it must exist (E)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="set" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="True if this element represents a set (S), false if it represents a particular (P)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="var" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="True if this element is a variable (V), false if it a constant (C)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collections" upperBound="-1"
        eType="#//MAVOCollection" eOpposite="#//MAVOCollection/mavoElements">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The list of collections this MAVO element is part of, possibly empty."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAVOReference" abstract="true" eSuperTypes="#//MAVOElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A MAVO element that was originally implemented as an EReference."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAVODecision" abstract="true" eSuperTypes="#//DecisionElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An abstract decision to be made within a MAVO model."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredDecisions" upperBound="-1"
        eType="#//MAVODecision">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The list of required decisions that must be resolved before resolving this decision."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAVOCollection" eSuperTypes="#//DecisionElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A collection of MAVO elements."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mavoElements" upperBound="-1"
        eType="#//MAVOElement" eOpposite="#//MAVOElement/collections">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The list of MAVO elements in this collection."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MayDecisionLogic">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The decision logic for May alternatives."/>
    </eAnnotations>
    <eLiterals name="XOR">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The XOR logic."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MayDecision" eSuperTypes="#//MAVODecision">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A May decision to be made within a MAVO model."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logic" lowerBound="1" eType="#//MayDecisionLogic">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The logic relationship between alternative options in this decision."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alternatives" lowerBound="1"
        upperBound="-1" eType="#//MAVOCollection" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The list of alternative options for this decision."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VarDecision" eSuperTypes="#//MAVODecision">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A Var decision to be made within a MAVO model."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domain" lowerBound="1"
        eType="#//MAVOCollection" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The merge domain for this decision."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
