<?xml version="1.0" encoding="ISO-8859-1"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="relationaldatabase_mavo" nsURI="http://se.cs.toronto.edu/modelepedia/RelationalDatabase_MAVO"
    nsPrefix="relationaldatabase_mavo">
  <eClassifiers xsi:type="ecore:EClass" name="RelationalDatabase" eSuperTypes="../../edu.toronto.cs.se.mavo/model/mavo.ecore#//MAVORoot">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tables" upperBound="-1"
        eType="#//Table" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="../../edu.toronto.cs.se.mavo/model/mavo.ecore#//MAVOElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table" eSuperTypes="#//NamedElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" lowerBound="1"
        upperBound="-1" eType="#//Column" containment="true" eOpposite="#//Column/table">
      <eAnnotations source="gmf.compartment">
        <details key="layout" value="list"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primaryKey" lowerBound="1"
        eType="#//Column" eOpposite="#//Column/tableAsPrimaryKey"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="foreignKeys" upperBound="-1"
        eType="#//ForeignKey" containment="true" eOpposite="#//ForeignKey/table">
      <eAnnotations source="gmf.compartment">
        <details key="layout" value="list"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Column" eSuperTypes="#//NamedElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" lowerBound="1" eType="#//Table"
        eOpposite="#//Table/columns"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tableAsPrimaryKey" eType="#//Table"
        eOpposite="#//Table/primaryKey"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="foreignKeysAsColumn" upperBound="-1"
        eType="#//TableColumnReference" eOpposite="#//TableColumnReference/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="foreignKeysAsForeignColumn"
        upperBound="-1" eType="#//ForeignColumnReference" eOpposite="#//ForeignColumnReference/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForeignKey" eSuperTypes="#//NamedElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tableColumn" lowerBound="1"
        upperBound="-1" eType="#//TableColumnReference" containment="true" eOpposite="#//TableColumnReference/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="foreignColumn" lowerBound="1"
        upperBound="-1" eType="#//ForeignColumnReference" containment="true" eOpposite="#//ForeignColumnReference/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" lowerBound="1" eType="#//Table"
        eOpposite="#//Table/foreignKeys"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableColumnReference" eSuperTypes="../../edu.toronto.cs.se.mavo/model/mavo.ecore#//MAVOReference">
    <eAnnotations source="gmf.link">
      <details key="target.decoration" value="none"/>
      <details key="source" value="source"/>
      <details key="target" value="target"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//ForeignKey" eOpposite="#//ForeignKey/tableColumn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Column" eOpposite="#//Column/foreignKeysAsColumn"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForeignColumnReference" eSuperTypes="../../edu.toronto.cs.se.mavo/model/mavo.ecore#//MAVOReference">
    <eAnnotations source="gmf.link">
      <details key="target.decoration" value="none"/>
      <details key="source" value="source"/>
      <details key="target" value="target"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//ForeignKey" eOpposite="#//ForeignKey/foreignColumn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Column" eOpposite="#//Column/foreignKeysAsForeignColumn"/>
  </eClassifiers>
</ecore:EPackage>
