<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="icse15_sequencediagram_mavo" nsURI="http://se.cs.toronto.edu/modelepedia/ICSE15_SequenceDiagram_MAVO"
    nsPrefix="icse15_sequencediagram_mavo">
  <eClassifiers xsi:type="ecore:EClass" name="SequenceDiagram" eSuperTypes="../../edu.toronto.cs.se.mavo/model/mavo.ecore#//MAVORoot">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lifelines" upperBound="-1"
        eType="#//Lifeline" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//Class" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" upperBound="-1"
        eType="#//Message" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" eSuperTypes="../../edu.toronto.cs.se.mavo/model/mavo.ecore#//MAVOElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lifeline" eSuperTypes="#//NamedElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="class" lowerBound="1" upperBound="-1"
        eType="#//ClassReference" containment="true" eOpposite="#//ClassReference/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messagesAsSource" upperBound="-1"
        eType="#//SourceLifelineReference" eOpposite="#//SourceLifelineReference/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messagesAsTarget" upperBound="-1"
        eType="#//TargetLifelineReference" eOpposite="#//TargetLifelineReference/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//NamedElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//Operation" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="layout" value="list"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lifelines" upperBound="-1"
        eType="#//ClassReference" eOpposite="#//ClassReference/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//NamedElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" upperBound="-1"
        eType="#//OperationReference" eOpposite="#//OperationReference/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message" eSuperTypes="#//NamedElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        upperBound="-1" eType="#//OperationReference" containment="true" eOpposite="#//OperationReference/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceLifeline" lowerBound="1"
        upperBound="-1" eType="#//SourceLifelineReference" containment="true" eOpposite="#//SourceLifelineReference/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetLifeline" lowerBound="1"
        upperBound="-1" eType="#//TargetLifelineReference" containment="true" eOpposite="#//TargetLifelineReference/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassReference" eSuperTypes="../../edu.toronto.cs.se.mavo/model/mavo.ecore#//MAVOReference">
    <eAnnotations source="gmf.link">
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="target.decoration" value="arrow"/>
      <details key="label.icon" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Lifeline" eOpposite="#//Lifeline/class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Class" eOpposite="#//Class/lifelines"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationReference" eSuperTypes="../../edu.toronto.cs.se.mavo/model/mavo.ecore#//MAVOReference">
    <eAnnotations source="gmf.link">
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="target.decoration" value="arrow"/>
      <details key="label.icon" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Message" eOpposite="#//Message/operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Operation" eOpposite="#//Operation/messages"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceLifelineReference" eSuperTypes="../../edu.toronto.cs.se.mavo/model/mavo.ecore#//MAVOReference">
    <eAnnotations source="gmf.link">
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="target.decoration" value="arrow"/>
      <details key="label.icon" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Message" eOpposite="#//Message/sourceLifeline"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Lifeline" eOpposite="#//Lifeline/messagesAsSource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TargetLifelineReference" eSuperTypes="../../edu.toronto.cs.se.mavo/model/mavo.ecore#//MAVOReference">
    <eAnnotations source="gmf.link">
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="target.decoration" value="arrow"/>
      <details key="label.icon" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Message" eOpposite="#//Message/targetLifeline"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Lifeline" eOpposite="#//Lifeline/messagesAsTarget"/>
  </eClassifiers>
</ecore:EPackage>
