<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="powerwindow" nsURI="http://se.cs.toronto.edu/modelepedia/powerwindow"
    nsPrefix="powerwindow">
  <eClassifiers xsi:type="ecore:EClass" name="Window" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensor" eType="#//Sensor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="switches" lowerBound="1"
        upperBound="-1" eType="#//Switch" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Infrared" eSuperTypes="#//Sensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForceDetecting" eSuperTypes="#//Sensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Switch" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="overridable" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LockOut" eSuperTypes="#//Switch"/>
  <eClassifiers xsi:type="ecore:EClass" name="Movement" abstract="true" eSuperTypes="#//Switch"/>
  <eClassifiers xsi:type="ecore:EClass" name="Rocker" eSuperTypes="#//Movement"/>
  <eClassifiers xsi:type="ecore:EClass" name="PushPull" eSuperTypes="#//Movement"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
