<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="istar" nsURI="http://se.cs.toronto.edu/modelepedia/IStar" nsPrefix="istar">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="IStar">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="onlyDependums"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="onlyDependums" value="dependums->forAll(linksAsSrc->isEmpty() and linksAsTgt->isEmpty())"/>
    </eAnnotations>
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actors" upperBound="-1"
        eType="#//Actor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependums" upperBound="-1"
        eType="#//Intention" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//DependencyEndpoint">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="noDependums"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="noDependums" value="intentions->forAll(dependerLinks->isEmpty() and dependeeLinks->isEmpty())"/>
    </eAnnotations>
    <eAnnotations source="gmf.node">
      <details key="figure" value="ellipse"/>
      <details key="border.style" value="dash"/>
      <details key="border.width" value="2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intentions" upperBound="-1"
        eType="#//Intention" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="layout" value="free"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Intention" abstract="true" eSuperTypes="#//DependencyEndpoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullySatisfied" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="partiallySatisfied" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unknown" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conflict" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="partiallyDenied" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullyDenied" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linksAsSrc" upperBound="-1"
        eType="#//IntentionLink" containment="true" eOpposite="#//IntentionLink/src"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linksAsTgt" upperBound="-1"
        eType="#//IntentionLink" eOpposite="#//IntentionLink/tgt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependerLinks" upperBound="-1"
        eType="#//DependerLink" containment="true" eOpposite="#//DependerLink/dependum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependeeLinks" upperBound="-1"
        eType="#//DependeeLink" containment="true" eOpposite="#//DependeeLink/dependum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//Intention">
    <eAnnotations source="gmf.node">
      <details key="figure" value="edu.toronto.cs.se.modelepedia.istar.diagram.figures.TaskFigure"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="#//Intention">
    <eAnnotations source="gmf.node">
      <details key="figure" value="rectangle"/>
      <details key="border.width" value="5"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Goal" eSuperTypes="#//Intention">
    <eAnnotations source="gmf.node">
      <details key="figure" value="edu.toronto.cs.se.modelepedia.istar.diagram.figures.GoalFigure"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoftGoal" eSuperTypes="#//Goal">
    <eAnnotations source="gmf.node">
      <details key="figure" value="edu.toronto.cs.se.modelepedia.istar.diagram.figures.SoftGoalFigure"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependencyEndpoint" abstract="true">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependenciesAsDepender"
        upperBound="-1" eType="#//DependerLink" eOpposite="#//DependerLink/depender"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependenciesAsDependee"
        upperBound="-1" eType="#//DependeeLink" eOpposite="#//DependeeLink/dependee"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntentionLink" abstract="true">
    <eAnnotations source="gmf.link">
      <details key="source" value="src"/>
      <details key="target" value="tgt"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="if src.oclIsUndefined() or tgt.oclIsUndefined() then '' else src.name.concat(' 2 ').concat(tgt.name) endif"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//Intention"
        eOpposite="#//Intention/linksAsSrc"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tgt" lowerBound="1" eType="#//Intention"
        eOpposite="#//Intention/linksAsTgt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeansEnd" eSuperTypes="#//IntentionLink">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="srcTask tgtGoal"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="srcTask" value="src.oclIsTypeOf(Task)"/>
      <details key="tgtGoal" value="tgt.oclIsTypeOf(Goal)"/>
    </eAnnotations>
    <eAnnotations source="gmf.link">
      <details key="target.decoration" value="closedarrow"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Decomposition" eSuperTypes="#//IntentionLink">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="tgtTask"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="tgtTask" value="tgt.oclIsTypeOf(Task)"/>
    </eAnnotations>
    <eAnnotations source="gmf.link">
      <details key="target.decoration" value="filledrhomb"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contribution" eSuperTypes="#//IntentionLink">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="tgtSoftgoal"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="tgtSoftgoal" value="tgt.oclIsTypeOf(SoftGoal)"/>
    </eAnnotations>
    <eAnnotations source="gmf.link">
      <details key="target.decoration" value="arrow"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//ContributionType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ContributionType">
    <eLiterals name="MAKE"/>
    <eLiterals name="HELP" value="1"/>
    <eLiterals name="SOMEPLUS" value="2"/>
    <eLiterals name="BREAK" value="3"/>
    <eLiterals name="HURT" value="4"/>
    <eLiterals name="SOMEMINUS" value="5"/>
    <eLiterals name="UNKNOWN" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependerLink">
    <eAnnotations source="gmf.link">
      <details key="target.decoration" value="arrow"/>
      <details key="source" value="depender"/>
      <details key="target" value="dependum"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="if depender.oclIsUndefined() or dependum.oclIsUndefined() then '' else depender.name.concat(' 2 ').concat(dependum.name) endif"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="depender" lowerBound="1"
        eType="#//DependencyEndpoint" eOpposite="#//DependencyEndpoint/dependenciesAsDepender"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependum" lowerBound="1"
        eType="#//Intention" eOpposite="#//Intention/dependerLinks"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependeeLink">
    <eAnnotations source="gmf.link">
      <details key="target.decoration" value="arrow"/>
      <details key="source" value="dependum"/>
      <details key="target" value="dependee"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="if dependum.oclIsUndefined() or dependee.oclIsUndefined() then '' else dependum.name.concat(' 2 ').concat(dependee.name) endif"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependum" lowerBound="1"
        eType="#//Intention" eOpposite="#//Intention/dependeeLinks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependee" lowerBound="1"
        eType="#//DependencyEndpoint" eOpposite="#//DependencyEndpoint/dependenciesAsDependee"/>
  </eClassifiers>
</ecore:EPackage>
