<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="istar" nsURI="http://se.cs.toronto.edu/modelepedia/mavo/IStar"
    nsPrefix="istar">
  <eClassifiers xsi:type="ecore:EClass" name="IStar">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actors" upperBound="-1"
        eType="#//Actor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="#//Dependency" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="../../edu.toronto.cs.se.mmtf.core/model/mavo.ecore#//MAVOElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="intentionalElements" upperBound="-1"
        eType="#//IntentionalElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependenciesAsDepender"
        upperBound="-1" eType="#//Depender" eOpposite="#//Depender/depender"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependenciesAsDependee"
        upperBound="-1" eType="#//Dependee" eOpposite="#//Dependee/dependee"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contributions" upperBound="-1"
        eType="#//Contribution" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decompositions" upperBound="-1"
        eType="#//Decomposition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="meansEnds" upperBound="-1"
        eType="#//MeansEnd" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dependency" eSuperTypes="../../edu.toronto.cs.se.mmtf.core/model/mavo.ecore#//MAVOElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="depender" lowerBound="1"
        eType="#//Depender" eOpposite="#//Depender/dependency"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependee" lowerBound="1"
        eType="#//Dependee" eOpposite="#//Dependee/dependency"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependum" lowerBound="1"
        eType="#//IntentionalElement" containment="true" eOpposite="#//IntentionalElement/dependency"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Depender" eSuperTypes="../../edu.toronto.cs.se.mmtf.core/model/mavo.ecore#//MAVOReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="depender" lowerBound="1"
        eType="#//Actor" eOpposite="#//Actor/dependenciesAsDepender"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependency" lowerBound="1"
        eType="#//Dependency" eOpposite="#//Dependency/depender"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dependee" eSuperTypes="../../edu.toronto.cs.se.mmtf.core/model/mavo.ecore#//MAVOReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependee" eType="#//Actor"
        eOpposite="#//Actor/dependenciesAsDependee"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependency" lowerBound="1"
        eType="#//Dependency" eOpposite="#//Dependency/dependee"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntentionalElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependency" eType="#//Dependency"
        eOpposite="#//Dependency/dependum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composite" eType="#//Decomposition"
        eOpposite="#//Decomposition/components"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contributionsAsContributor"
        upperBound="-1" eType="#//Contribution" eOpposite="#//Contribution/contributor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//IntentionalElement ../../edu.toronto.cs.se.mmtf.core/model/mavo.ecore#//MAVOElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Decomposition" eOpposite="#//Decomposition/composite"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//MeansEnd"
        eOpposite="#//MeansEnd/means"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="#//IntentionalElement ../../edu.toronto.cs.se.mmtf.core/model/mavo.ecore#//MAVOElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Goal" eSuperTypes="#//IntentionalElement ../../edu.toronto.cs.se.mmtf.core/model/mavo.ecore#//MAVOElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="means" upperBound="-1"
        eType="#//MeansEnd" eOpposite="#//MeansEnd/end"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoftGoal" eSuperTypes="#//Goal">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contributionsAsContributee"
        upperBound="-1" eType="#//Contribution" eOpposite="#//Contribution/contributee"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contribution" eSuperTypes="../../edu.toronto.cs.se.mmtf.core/model/mavo.ecore#//MAVOElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contributor" lowerBound="1"
        eType="#//IntentionalElement" eOpposite="#//IntentionalElement/contributionsAsContributor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contributee" lowerBound="1"
        eType="#//SoftGoal" eOpposite="#//SoftGoal/contributionsAsContributee"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeansEnd" eSuperTypes="../../edu.toronto.cs.se.mmtf.core/model/mavo.ecore#//MAVOReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="means" lowerBound="1" upperBound="-1"
        eType="#//Task" eOpposite="#//Task/end"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="1" eType="#//Goal"
        eOpposite="#//Goal/means"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Decomposition" eSuperTypes="../../edu.toronto.cs.se.mmtf.core/model/mavo.ecore#//MAVOReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composite" lowerBound="1"
        eType="#//Task" eOpposite="#//Task/components"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" lowerBound="1"
        upperBound="-1" eType="#//IntentionalElement" eOpposite="#//IntentionalElement/composite"/>
  </eClassifiers>
</ecore:EPackage>
