<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="crom_l1" nsURI="http://crom_l1/1.0" nsPrefix="crom_l1">
  <eAnnotations source="features">
    <details key="file" value="model.xml"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" abstract="true" interface="true"
      eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
        eType="#//Relation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ModelElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RigidType" eSuperTypes="#//Type #//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Group" eSuperTypes="#//ModelElement #//Model"/>
  <eClassifiers xsi:type="ecore:EClass" name="Relation" abstract="true">
    <eAnnotations source="modifier">
      <details key="condition" value="OnRelationships"/>
      <details key="extend" value="Relationship"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//TypedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//TypedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//Type"
        eOpposite="#//Type/operations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//TypedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//Type"
        eOpposite="#//Type/attributes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" eSuperTypes="#//RelationTarget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true" eOpposite="#//Attribute/owner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//Operation" containment="true" eOpposite="#//Operation/owner"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NaturalType" eSuperTypes="#//RigidType">
    <eAnnotations source="modifier">
      <details key="condition" value="not Compartments and Roles"/>
      <details key="extend" value="Player"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleType" eSuperTypes="#//AbstractRole #//RelationTarget">
    <eAnnotations source="modifier">
      <details key="condition" value="not Compartments and Roles"/>
      <details key="extend" value="Player"/>
    </eAnnotations>
    <eAnnotations source="modifier">
      <details key="condition" value="RoleBehavior and RoleProperties"/>
      <details key="extend" value="AntiRigidType"/>
    </eAnnotations>
    <eAnnotations source="modifier">
      <details key="condition" value="RoleProperties"/>
      <details key="extend" value="AntiRigidType"/>
    </eAnnotations>
    <eAnnotations source="modifier">
      <details key="condition" value="not RoleProperties"/>
      <details key="extend" value="RelationTarget"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fulfillment" eSuperTypes="#//Relation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filled" lowerBound="1"
        eType="#//AbstractRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fillerType" lowerBound="1"
        eType="#//Type">
      <eAnnotations source="presence">
        <details key="condition" value="Compartments and Roles"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fillerRType" lowerBound="1"
        eType="#//RigidType">
      <eAnnotations source="presence">
        <details key="condition" value="Compartments and not Roles"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fillerPlayer" lowerBound="1"
        eType="#//Player">
      <eAnnotations source="presence">
        <details key="condition" value="not Compartments and Roles"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fillerNType" lowerBound="1"
        eType="#//NaturalType">
      <eAnnotations source="presence">
        <details key="condition" value="not Compartments and not Roles"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inheritance" eSuperTypes="#//Relation"/>
  <eClassifiers xsi:type="ecore:EClass" name="NaturalInheritance" eSuperTypes="#//Inheritance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="super" lowerBound="1" eType="#//NaturalType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sub" lowerBound="1" eType="#//NaturalType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationTarget" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//Relation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//Relation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractRole" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//RoleModel"
        eOpposite="#//RoleModel/roles">
      <eAnnotations source="presence">
        <details key="condition" value="not OnCompartments"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="whole" lowerBound="1" eType="#//CompartmentType"
        eOpposite="#//CompartmentType/parts">
      <eAnnotations source="presence">
        <details key="condition" value="OnCompartments"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleModel" eSuperTypes="#//ModelElement">
    <eAnnotations source="presence">
      <details key="condition" value="not OnCompartments"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" ordered="false"
        upperBound="-1" eType="#//AbstractRole" containment="true" eOpposite="#//AbstractRole/model">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedElement" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompartmentType" eSuperTypes="#//RigidType">
    <eAnnotations source="presence">
      <details key="condition" value="OnCompartments"/>
    </eAnnotations>
    <eAnnotations source="modifier">
      <details key="condition" value="CompartmentBehavior or CompartmentProperties"/>
      <details key="extend" value="RigidType"/>
    </eAnnotations>
    <eAnnotations source="modifier">
      <details key="condition" value="not CompartmentBehavior and not CompartmentProperties"/>
      <details key="extend" value="ModelElement"/>
    </eAnnotations>
    <eAnnotations source="modifier">
      <details key="condition" value="ContainsCompartments and OnCompartments"/>
      <details key="extend" value="AbstractRole"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parts" ordered="false"
        upperBound="-1" eType="#//AbstractRole" containment="true" eOpposite="#//AbstractRole/whole">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationships" ordered="false"
        upperBound="-1" eType="#//Relationship" containment="true">
      <eAnnotations source="presence">
        <details key="condition" value="OnCompartments and OnRelationships"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" ordered="false"
        upperBound="-1" eType="#//Constraint" containment="true">
      <eAnnotations source="presence">
        <details key="condition" value="(RelationshipConstraints or RoleConstraints) and OnCompartments"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Player" abstract="true" interface="true">
    <eAnnotations source="presence">
      <details key="condition" value="not Compartments and Roles"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompartmentInheritance" eSuperTypes="#//Inheritance">
    <eAnnotations source="presence">
      <details key="condition" value="CompartmentInheritance"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="super" lowerBound="1" eType="#//CompartmentType">
      <eAnnotations source="presence">
        <details key="condition" value="CompartmentInheritance and OnCompartments"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sub" lowerBound="1" eType="#//CompartmentType">
      <eAnnotations source="presence">
        <details key="condition" value="CompartmentInheritance and OnCompartments"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleGroup" eSuperTypes="#//AbstractRole #//RelationTarget">
    <eAnnotations source="presence">
      <details key="condition" value="GroupConstraints"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//AbstractRole">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterRelationshipConstraint" eSuperTypes="#//RelationshipConstraint">
    <eAnnotations source="presence">
      <details key="condition" value="InterRelationshipConstraints"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="first" lowerBound="1" eType="#//Relationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="second" lowerBound="1"
        eType="#//Relationship"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship">
    <eAnnotations source="presence">
      <details key="condition" value="OnRelationships"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="first" lowerBound="1" eType="#//Place"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="second" lowerBound="1"
        eType="#//Place"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipImplication" eSuperTypes="#//InterRelationshipConstraint">
    <eAnnotations source="presence">
      <details key="condition" value="InterRelationshipConstraints"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntraRelationshipConstraint" eSuperTypes="#//RelationshipConstraint">
    <eAnnotations source="presence">
      <details key="condition" value="IntraRelationshipConstraints"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relation" lowerBound="1"
        eType="#//Relationship"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cyclic" eSuperTypes="#//IntraRelationshipConstraint">
    <eAnnotations source="presence">
      <details key="condition" value="IntraRelationshipConstraints"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Total" eSuperTypes="#//IntraRelationshipConstraint">
    <eAnnotations source="presence">
      <details key="condition" value="IntraRelationshipConstraints"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Irreflexive" eSuperTypes="#//IntraRelationshipConstraint">
    <eAnnotations source="presence">
      <details key="condition" value="IntraRelationshipConstraints"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Parthood">
    <eAnnotations source="presence">
      <details key="condition" value="OnRelationships"/>
    </eAnnotations>
    <eLiterals name="Unconstrained"/>
    <eLiterals name="ExclusivePart"/>
    <eLiterals name="EssentialPart"/>
    <eLiterals name="MandatoryPart"/>
    <eLiterals name="InseparablePart"/>
    <eLiterals name="ShareablePart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Place">
    <eAnnotations source="presence">
      <details key="condition" value="OnRelationships"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="part" lowerBound="1" eType="#//Parthood"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="holder" lowerBound="1"
        eType="#//RoleType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipConstraint" eSuperTypes="#//Constraint">
    <eAnnotations source="presence">
      <details key="condition" value="RelationshipConstraints"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint">
    <eAnnotations source="presence">
      <details key="condition" value="RelationshipConstraints or RoleConstraints"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AntiRigidType" eSuperTypes="#//Type">
    <eAnnotations source="presence">
      <details key="condition" value="RoleBehavior and RoleProperties"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleConstraint" eSuperTypes="#//Constraint">
    <eAnnotations source="presence">
      <details key="condition" value="RoleConstraints"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="first" lowerBound="1" eType="#//AbstractRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="second" lowerBound="1"
        eType="#//AbstractRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleEquivalence" eSuperTypes="#//RoleConstraint">
    <eAnnotations source="presence">
      <details key="condition" value="RoleEquivalence"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleImplication" eSuperTypes="#//RoleConstraint">
    <eAnnotations source="presence">
      <details key="condition" value="RoleImplication"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleInheritance" eSuperTypes="#//Inheritance">
    <eAnnotations source="presence">
      <details key="condition" value="RoleInheritance"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="super" lowerBound="1" eType="#//RoleType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sub" lowerBound="1" eType="#//RoleType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleProhibition" eSuperTypes="#//RoleConstraint">
    <eAnnotations source="presence">
      <details key="condition" value="RoleProhibition"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
