/**
 * Copyright (c) 2012-2025 Marsha Chechik, Alessio Di Sandro, Michalis Famelis,
 * Rick Salay.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Alessio Di Sandro - Implementation.
 */
package edu.toronto.cs.se.mmint.mid.provider;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.common.util.ResourceLocator;
import org.eclipse.emf.edit.domain.EditingDomain;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ChildCreationExtenderManager;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IChildCreationExtender;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import edu.toronto.cs.se.mmint.mid.MIDPackage;
import edu.toronto.cs.se.mmint.mid.util.MIDAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class MIDItemProviderAdapterFactory extends MIDAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable, IChildCreationExtender {
	/**
   * This keeps track of the root adapter factory that delegates to this adapter factory.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
   * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
   * This helps manage the child creation extenders.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected ChildCreationExtenderManager childCreationExtenderManager = new ChildCreationExtenderManager(MIDEditPlugin.INSTANCE, MIDPackage.eNS_URI);

	/**
   * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected Collection<Object> supportedTypes = new ArrayList<>();

	/**
   * This constructs an instance.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	public MIDItemProviderAdapterFactory() {
    this.supportedTypes.add(IEditingDomainItemProvider.class);
    this.supportedTypes.add(IStructuredItemContentProvider.class);
    this.supportedTypes.add(ITreeItemContentProvider.class);
    this.supportedTypes.add(IItemLabelProvider.class);
    this.supportedTypes.add(IItemPropertySource.class);
  }

	/**
   * This keeps track of the one adapter used for all {@link edu.toronto.cs.se.mmint.mid.MID} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected MIDItemProvider midItemProvider;

	/**
   * This creates an adapter for a {@link edu.toronto.cs.se.mmint.mid.MID}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createMIDAdapter() {
    if (this.midItemProvider == null) {
      this.midItemProvider = new MIDItemProvider(this);
    }

    return this.midItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link java.util.Map.Entry} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected EStringToExtendibleElementMapItemProvider eStringToExtendibleElementMapItemProvider;

	/**
   * This creates an adapter for a {@link java.util.Map.Entry}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createEStringToExtendibleElementMapAdapter() {
    if (this.eStringToExtendibleElementMapItemProvider == null) {
      this.eStringToExtendibleElementMapItemProvider = new EStringToExtendibleElementMapItemProvider(this);
    }

    return this.eStringToExtendibleElementMapItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link edu.toronto.cs.se.mmint.mid.Model} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected ModelItemProvider modelItemProvider;

	/**
   * This creates an adapter for a {@link edu.toronto.cs.se.mmint.mid.Model}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createModelAdapter() {
    if (this.modelItemProvider == null) {
      this.modelItemProvider = new ModelItemProvider(this);
    }

    return this.modelItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link edu.toronto.cs.se.mmint.mid.ExtendibleElementConstraint} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected ExtendibleElementConstraintItemProvider extendibleElementConstraintItemProvider;

	/**
   * This creates an adapter for a {@link edu.toronto.cs.se.mmint.mid.ExtendibleElementConstraint}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createExtendibleElementConstraintAdapter() {
    if (this.extendibleElementConstraintItemProvider == null) {
      this.extendibleElementConstraintItemProvider = new ExtendibleElementConstraintItemProvider(this);
    }

    return this.extendibleElementConstraintItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link edu.toronto.cs.se.mmint.mid.ModelElement} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected ModelElementItemProvider modelElementItemProvider;

	/**
   * This creates an adapter for a {@link edu.toronto.cs.se.mmint.mid.ModelElement}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createModelElementAdapter() {
    if (this.modelElementItemProvider == null) {
      this.modelElementItemProvider = new ModelElementItemProvider(this);
    }

    return this.modelElementItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link edu.toronto.cs.se.mmint.mid.ModelEndpoint} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected ModelEndpointItemProvider modelEndpointItemProvider;

	/**
   * This creates an adapter for a {@link edu.toronto.cs.se.mmint.mid.ModelEndpoint}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createModelEndpointAdapter() {
    if (this.modelEndpointItemProvider == null) {
      this.modelEndpointItemProvider = new ModelEndpointItemProvider(this);
    }

    return this.modelEndpointItemProvider;
  }

	/**
   * This keeps track of the one adapter used for all {@link edu.toronto.cs.se.mmint.mid.EMFInfo} instances.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	protected EMFInfoItemProvider emfInfoItemProvider;

	/**
   * This creates an adapter for a {@link edu.toronto.cs.se.mmint.mid.EMFInfo}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter createEMFInfoAdapter() {
    if (this.emfInfoItemProvider == null) {
      this.emfInfoItemProvider = new EMFInfoItemProvider(this);
    }

    return this.emfInfoItemProvider;
  }

	/**
   * This returns the root adapter factory that contains this factory.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
  public ComposeableAdapterFactory getRootAdapterFactory() {
    return this.parentAdapterFactory == null ? this : this.parentAdapterFactory.getRootAdapterFactory();
  }

	/**
   * This sets the composed adapter factory that contains this factory.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
  public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
    this.parentAdapterFactory = parentAdapterFactory;
  }

	/**
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public boolean isFactoryForType(Object type) {
    return this.supportedTypes.contains(type) || super.isFactoryForType(type);
  }

	/**
   * This implementation substitutes the factory itself as the key for the adapter.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
    return super.adapt(notifier, this);
  }

	/**
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
	public Object adapt(Object object, Object type) {
    if (isFactoryForType(type)) {
      var adapter = super.adapt(object, type);
      if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
        return adapter;
      }
    }

    return null;
  }

	/**
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	public List<IChildCreationExtender> getChildCreationExtenders() {
    return this.childCreationExtenderManager.getChildCreationExtenders();
  }

	/**
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
  public Collection<?> getNewChildDescriptors(Object object, EditingDomain editingDomain) {
    return this.childCreationExtenderManager.getNewChildDescriptors(object, editingDomain);
  }

	/**
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
  public ResourceLocator getResourceLocator() {
    return this.childCreationExtenderManager;
  }

	/**
   * This adds a listener.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
  public void addListener(INotifyChangedListener notifyChangedListener) {
    this.changeNotifier.addListener(notifyChangedListener);
  }

	/**
   * This removes a listener.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
  public void removeListener(INotifyChangedListener notifyChangedListener) {
    this.changeNotifier.removeListener(notifyChangedListener);
  }

	/**
   * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
  public void fireNotifyChanged(Notification notification) {
    this.changeNotifier.fireNotifyChanged(notification);

    if (this.parentAdapterFactory != null) {
      this.parentAdapterFactory.fireNotifyChanged(notification);
    }
  }

	/**
   * This disposes all of the item providers created by this factory.
   * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
   * @generated
   */
	@Override
  public void dispose() {
    if (this.midItemProvider != null) {
      this.midItemProvider.dispose();
    }
    if (this.eStringToExtendibleElementMapItemProvider != null) {
      this.eStringToExtendibleElementMapItemProvider.dispose();
    }
    if (this.modelItemProvider != null) {
      this.modelItemProvider.dispose();
    }
    if (this.extendibleElementConstraintItemProvider != null) {
      this.extendibleElementConstraintItemProvider.dispose();
    }
    if (this.modelElementItemProvider != null) {
      this.modelElementItemProvider.dispose();
    }
    if (this.modelEndpointItemProvider != null) {
      this.modelEndpointItemProvider.dispose();
    }
    if (this.emfInfoItemProvider != null) {
      this.emfInfoItemProvider.dispose();
    }
  }

}
