<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mid" nsURI="http:///edu/toronto/cs/se/mmtf/model/mid.ecore"
    nsPrefix="mid">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendibleElement" abstract="true" eSuperTypes="#//TypedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="supertypeType"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="supertypeType" value="not supertype.oclIsUndefined() implies self.oclIsKindOf(supertype.oclType())"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supertype" eType="#//ExtendibleElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="models" upperBound="-1"
        eType="#//Model" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editors" upperBound="-1"
        eType="#//editor/EStringToEditorMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operators" upperBound="-1"
        eType="#//operator/Operator" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendibleTable" upperBound="-1"
        eType="#//EStringToExtendibleElementMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operatorTable" upperBound="-1"
        eType="#//operator/EStringToOperatorMap" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//ExtendibleElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="origin" lowerBound="1"
        eType="#//ModelOrigin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileExtension" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editors" upperBound="-1"
        eType="#//editor/Editor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ModelElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MidLevel">
    <eLiterals name="INSTANCES"/>
    <eLiterals name="TYPES" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ModelOrigin">
    <eLiterals name="IMPORTED"/>
    <eLiterals name="CREATED" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedElement" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="typeLevel"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="typeLevel" value="level = MidLevel::INSTANCES implies metatype.level = MidLevel::TYPES"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metatype" eType="#//TypedElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" lowerBound="1" eType="#//MidLevel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="if metatype.oclIsUndefined() then '' else metatype.name endif"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EStringToExtendibleElementMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//ExtendibleElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" eSuperTypes="#//ExtendibleElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" lowerBound="1"
        eType="#//ModelElementCategory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pointer" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ModelElementCategory">
    <eLiterals name="ENTITY"/>
    <eLiterals name="RELATIONSHIP" value="1"/>
  </eClassifiers>
  <eSubpackages name="relationship" nsURI="http:///edu/toronto/cs/se/mmtf/model/mid.ecore/relationship"
      nsPrefix="relationship">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="ModelRel" eSuperTypes="#//Model">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="unboundedLevel modelRefs"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="unboundedLevel" value="unbounded = true implies level = MidLevel::TYPES"/>
        <details key="modelRefs" value="models->size() = modelRefs->size()"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="models" lowerBound="1"
          upperBound="-1" eType="#//Model"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
          eType="#//relationship/Link" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="modelRefs" lowerBound="1"
          upperBound="-1" eType="#//relationship/ModelReference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unbounded" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BinaryModelRel" eSuperTypes="#//relationship/ModelRel">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="isBinaryRel"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="isBinaryRel" value="models->size() = 2"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HomomorphismModelRel" eSuperTypes="#//relationship/BinaryModelRel">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="sameModelTypes"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="sameModelTypes" value="models->forAll(m1 : Model, m2 : Model | m1.type = m2.type)"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModelReference" eSuperTypes="#//relationship/TypedElementReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elementRefs" upperBound="-1"
          eType="#//relationship/ModelElementReference" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModelElementReference" eSuperTypes="#//relationship/TypedElementReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
          eType="#//relationship/Link" eOpposite="#//relationship/Link/elementRefs"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//ExtendibleElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="unboundedLevel"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="unboundedLevel" value="unbounded = true implies level = MidLevel::TYPES"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elementRefs" upperBound="-1"
          eType="#//relationship/ModelElementReference" eOpposite="#//relationship/ModelElementReference/links"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unbounded" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BinaryLink" eSuperTypes="#//relationship/Link">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="isBinaryLink"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="isBinaryLink" value="elementRefs->size() = 2"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HomomorphismLink" eSuperTypes="#//relationship/BinaryLink">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="sameElementTypes"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="sameElementTypes" value="invalid->forAll(e1 : ModelElement, e2 : ModelElement | e1.pointer.oclType() = e2.pointer.oclType())"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypedElementReference" abstract="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="oneObject"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="oneObject" value="referencedObject.oclIsUndefined() xor containedObject.oclIsUndefined()"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="referencedObject" eType="#//TypedElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="containedObject" eType="#//TypedElement"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="1"
          eType="#//TypedElement" changeable="false" volatile="true" transient="true"
          derived="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="derivation" value="if containedObject.oclIsUndefined() then referencedObject else containedObject endif"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false" volatile="true" transient="true" derived="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="derivation" value="if object.oclIsUndefined() then '' else object.name endif"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false" volatile="true" transient="true" derived="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="derivation" value="if object.oclIsUndefined() then '' else object.type endif"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="editor" nsURI="http:///edu/toronto/cs/se/mmtf/model/mid.ecore/editor"
      nsPrefix="editor">
    <eClassifiers xsi:type="ecore:EClass" name="EStringToEditorMap" instanceClassName="java.util.Map$Entry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
          eType="#//editor/Editor" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Editor" eSuperTypes="#//TypedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelUri" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="wizardId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileExtensions" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Diagram" eSuperTypes="#//editor/Editor"/>
  </eSubpackages>
  <eSubpackages name="operator" nsURI="http:///edu/toronto/cs/se/mmtf/model/mid.ecore/operator"
      nsPrefix="operator">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="EStringToParameterMap" instanceClassName="java.util.Map$Entry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
          eType="#//operator/Parameter"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Operator" eSuperTypes="#//TypedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
          eType="#//operator/Parameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
          eType="#//operator/Parameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="signatureTable" upperBound="-1"
          eType="#//operator/EStringToParameterMap" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="isModelParameter"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="isModelParameter" value="type = ParameterType::MODEL or type = ParameterType::MODEL_REL implies self.oclIsKindOf(ModelParameter)"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#//operator/ParameterType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vararg" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ParameterType">
      <eLiterals name="MODEL"/>
      <eLiterals name="MODEL_REL" value="1"/>
      <eLiterals name="BOOL" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModelParameter" eSuperTypes="#//operator/Parameter">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelUri" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1"
          eType="#//Model"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EStringToOperatorMap" instanceClassName="java.util.Map$Entry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
          eType="#//operator/Operator"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CoercionOperator" eSuperTypes="#//operator/Operator">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="coercion"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="coercion" value="inputs->size() = 1 and outputs->size() = 2 and inputs->forAll(value.oclIsKindOf(ModelParameter)) and outputs->forAll(value.oclIsKindOf(ModelParameter)) and inputs->at(1).value.oclAsType(ModelParameter).model.supertype = outputs->at(1).value.oclAsType(ModelParameter).model"/>
      </eAnnotations>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
