package edu.toronto.cs.se.mmtf;

/**
 * Custom exception for the model management project.
 *
 * @author Alessio Di Sandro
 */
public class MMTFException extends Exception {

	/** Exception types. */
	public enum Type {WARNING, ERROR}

	/** Autogenerated. */
	private static final long serialVersionUID = 1L;

	/**
	 * Prints an exception.
	 *
	 * @param type    The exception category.
	 * @param message The exception message.
	 * @param e       The exception or error.
	 */
	public static void print(Type type, String message, Throwable e) {

		switch (type) {
			case WARNING:
				message = "WARNING: " + message;
				break;
			case ERROR:
				message = "ERROR: " + message;
				break;
			default:
				message = "UNKNOWN PROBLEM: " + message;
		}
		System.err.println(message);
		System.err.println(" -> " + e.getMessage());

		if (type == Type.ERROR) {
			e.printStackTrace();
			System.exit(-1);
		}
	}

	/**
	 * Constructor: initializes superclass.
	 *
	 * @param message The exception message.
	 */
	public MMTFException(String message) {

		super(message);
	}

	/**
	 * Constructor: initializes superclass with a chained exception.
	 *
	 * @param message The exception message.
	 * @param cause   The exception that caused this exception.
	 */
	public MMTFException(String message, Throwable cause) {

		super(message, cause);
	}

}
