<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mm" nsURI="edu.toronto.cs.se.mmint.mm" nsPrefix="mm">
  <eClassifiers xsi:type="ecore:EClass" name="MegaModel" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="models" upperBound="-1"
        eType="#//Model" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MMElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeMegaModel" eSuperTypes="#//MegaModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceMegaModel" eSuperTypes="#//MegaModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="Model" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelType" eSuperTypes="#//Model #//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="t" lowerBound="1" eType="#//MMType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelInstance" eSuperTypes="#//Model #//Instance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="i" lowerBound="1" eType="#//MMInstance"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instance" abstract="true" interface="true">
    <eOperations name="getType" lowerBound="1" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MMInstance" abstract="true" eSuperTypes="#//MMElement #//Instance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MMType" abstract="true" eSuperTypes="#//MMElement #//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//Type"/>
  </eClassifiers>
</ecore:EPackage>
