<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gsn" nsURI="http://www.cs.toronto.edu/~nlsfung/gsn" nsPrefix="gsn">
  <eClassifiers xsi:type="ecore:EClass" name="SafetyCase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//GsnElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GsnElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="id"/>
        <details key="namespace" value="http://sdq.ipd.uka.de/Identifier/1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GoalSupport" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="StrategySupport" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Goal" eSuperTypes="#//GsnElement #//StrategySupport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//TruthState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedBy" lowerBound="1"
        eType="#//GoalSupport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inContextOf" upperBound="-1"
        eType="#//Context"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Strategy" eSuperTypes="#//GsnElement #//GoalSupport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//ValidityState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedBy" lowerBound="1"
        upperBound="-1" eType="#//StrategySupport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inContextOf" upperBound="-1"
        eType="#//Context"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Solution" eSuperTypes="#//GsnElement #//GoalSupport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//ValidityState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Context" eSuperTypes="#//GsnElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//ValidityState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASIL" eSuperTypes="#//Context">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="#//ASILLevel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TruthState">
    <eLiterals name="False" literal="False"/>
    <eLiterals name="True" value="1" literal="True"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ASILLevel">
    <eLiterals name="D" literal="D"/>
    <eLiterals name="C" value="1" literal="C"/>
    <eLiterals name="B" value="2" literal="B"/>
    <eLiterals name="A" value="3" literal="A"/>
    <eLiterals name="QM" value="4" literal="QM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ValidityState">
    <eLiterals name="Invalid" literal="Invalid"/>
    <eLiterals name="Valid" value="1" literal="Valid"/>
  </eClassifiers>
</ecore:EPackage>
