<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mid" nsURI="http:///edu/toronto/cs/se/mmtf/mid/model/mid.ecore"
    nsPrefix="mid">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ModelReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelReference" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="origin" lowerBound="1"
        eType="#//ModelReferenceOrigin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ModelReferenceOrigin">
    <eLiterals name="IMPORTED"/>
    <eLiterals name="CREATED" value="1"/>
  </eClassifiers>
  <eSubpackages name="mapping" nsURI="http:///edu/toronto/cs/se/mmtf/mid/model/mid.ecore/mapping"
      nsPrefix="mapping">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="MappingReference" eSuperTypes="#//ModelReference">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="modelContainers"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="modelContainers" value="models->size() = containers->size()"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="models" lowerBound="1"
          upperBound="-1" eType="#//ModelReference"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
          eType="#//mapping/Mapping" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="containers" lowerBound="1"
          upperBound="-1" eType="#//mapping/ModelContainer" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BinaryMappingReference" eSuperTypes="#//mapping/MappingReference">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="isBinary sourceModel targetModel"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="isBinary" value="models->size() = 2"/>
        <details key="sourceModel" value="model0 = models->at(0)"/>
        <details key="targetModel" value="model1 = models->at(1)"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="model0" lowerBound="1"
          eType="#//ModelReference"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="model1" lowerBound="1"
          eType="#//ModelReference"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModelContainer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
          eType="#//mapping/ModelElementReference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false" volatile="true" transient="true" derived="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="derivation" value="model.name"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1"
          eType="#//ModelReference"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModelElementReference" eSuperTypes="#//NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pointer" lowerBound="1"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
          eType="#//mapping/Mapping" eOpposite="#//mapping/Mapping/elements"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Mapping" eSuperTypes="#//NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
          eType="#//mapping/ModelElementReference" eOpposite="#//mapping/ModelElementReference/mappings"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
