<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sequencediagram" nsURI="http://se.cs.toronto.edu/modelepedia/SequenceDiagram"
    nsPrefix="sequencediagram">
  <eClassifiers xsi:type="ecore:EClass" name="SequenceDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1"
        eType="#//Object" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" upperBound="-1"
        eType="#//Message" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lifeline" eType="#//Lifeline"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//Object"/>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//Object">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lifeline">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activationBoxes" upperBound="-1"
        eType="#//ActivationBox" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivationBox">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activationBoxes" upperBound="-1"
        eType="#//ActivationBox" containment="true" eOpposite="#//ActivationBox/ownerActivationBox"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messagesAsSource" upperBound="-1"
        eType="#//Message" eOpposite="#//Message/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messagesAsTarget" upperBound="-1"
        eType="#//Message" eOpposite="#//Message/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownerActivationBox" eType="#//ActivationBox"
        eOpposite="#//ActivationBox/activationBoxes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//MessageType"
        defaultValueLiteral="Synchronous"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//ActivationBox" eOpposite="#//ActivationBox/messagesAsSource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//ActivationBox" eOpposite="#//ActivationBox/messagesAsTarget"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="guard" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predecessor" eType="#//Message"
        eOpposite="#//Message/successor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="successor" eType="#//Message"
        eOpposite="#//Message/predecessor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MessageType">
    <eLiterals name="Synchronous"/>
    <eLiterals name="Asynchronous" value="1"/>
    <eLiterals name="Return" value="2"/>
  </eClassifiers>
</ecore:EPackage>
