<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gsn" nsURI="http://se.cs.toronto.edu/modelepedia/GSN" nsPrefix="gsn">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="SafetyCase">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="SingleRoot"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="SingleRoot" value="Supporter.allInstances() -> &#xA;&#x9;&#x9;&#x9;select(d | d.supports.source -> isEmpty()) -> size() = 1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="goals" upperBound="-1"
        eType="#//Goal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="strategies" upperBound="-1"
        eType="#//Strategy" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="solutions" upperBound="-1"
        eType="#//Solution" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contexts" upperBound="-1"
        eType="#//Context" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="justifications" upperBound="-1"
        eType="#//Justification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assumptions" upperBound="-1"
        eType="#//Assumption" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectors" upperBound="-1"
        eType="#//SupportConnector" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArgumentElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="gmf.label">
        <details key="label" value="description"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentValidity" eType="#//ValidityValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="status" eType="#//ImpactAnnotation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatefulElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stateValidity" eType="#//ValidityValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASILfulElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="asil" eType="#//ASIL" containment="true"
        eOpposite="#//ASIL/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreElement" abstract="true" eSuperTypes="#//ArgumentElement #//Supporter"/>
  <eClassifiers xsi:type="ecore:EClass" name="DecomposableCoreElement" abstract="true"
      eSuperTypes="#//Supportable #//CoreElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inContextOf" upperBound="-1"
        eType="#//InContextOf" containment="true" eOpposite="#//InContextOf/contextOf"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextualElement" abstract="true" eSuperTypes="#//ArgumentElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ContextualElementSupporter ContextualElementContext"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ContextualElementSupporter" value="self.oclAsType(DecomposableCoreElement).oclIsInvalid()"/>
      <details key="ContextualElementContext" value="self.oclAsType(DecomposableCoreElement).oclIsInvalid()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextOf" lowerBound="1"
        upperBound="-1" eType="#//InContextOf" eOpposite="#//InContextOf/context"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SupportedBy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Supportable" eOpposite="#//Supportable/supportedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Supporter" eOpposite="#//Supporter/supports"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InContextOf">
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
        eType="#//ContextualElement" eOpposite="#//ContextualElement/contextOf"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextOf" lowerBound="1"
        eType="#//DecomposableCoreElement" eOpposite="#//DecomposableCoreElement/inContextOf"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Goal" abstract="true" eSuperTypes="#//DecomposableCoreElement #//StatefulElement #//ASILfulElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="GoalSupporter GoalContext ASILInheritance"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="GoalSupporter" value="&#xA;&#x9;&#x9;&#x9;let children : Set(Supporter) = self.supportedBy.target -> closure(p | if p.oclIsKindOf(CoreElement) then p.oclAsSet() else p.oclAsType(Supportable).supportedBy.target endif) -> asSet()&#xA;&#x9;&#x9;&#x9;in children -> selectByKind(CoreElement) -> forAll(s | s.oclIsKindOf(Goal) or s.oclIsKindOf(Strategy) or s.oclIsKindOf(Solution))"/>
      <details key="GoalContext" value="self.inContextOf.context -> forAll(c | c.oclIsKindOf(Context) or c.oclIsKindOf(Assumption) or c.oclIsKindOf(Justification))"/>
      <details key="ASILInheritance" value="&#xA;&#x9;&#x9;&#x9;let parents : Set(Goal) = self.supports.source -> closure(c | if c.oclIsKindOf(Goal) or c.oclIsKindOf(ASILDecompositionStrategy) then c.oclAsSet() else c.supports.source endif) -> selectByKind(Goal) -> asSet()&#xA;&#x9;&#x9;&#x9;in parents -> forAll(g | if g.asil = null then true else if self.asil = null then false else g.asil.value = ASILLevel::QM or (g.asil.value.toString() &lt;= self.asil.value.toString() and self.asil.value &lt;> ASILLevel::QM) endif endif)"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicGoal" eSuperTypes="#//Goal"/>
  <eClassifiers xsi:type="ecore:EClass" name="IndependenceGoal" eSuperTypes="#//Goal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Strategy" abstract="true" eSuperTypes="#//DecomposableCoreElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="StrategySupporter StrategyContext"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="StrategySupporter" value="&#xA;&#x9;&#x9;&#x9;let children : Set(Supporter) = self.supportedBy.target -> closure(p | if p.oclIsKindOf(CoreElement) then p.oclAsSet() else p.oclAsType(Supportable).supportedBy.target endif) -> asSet() &#xA;&#x9;&#x9;&#x9;in children -> selectByKind(CoreElement) -> forAll(s | s.oclIsKindOf(Goal) or s.oclIsKindOf(Solution))"/>
      <details key="StrategyContext" value="self.inContextOf.context -> forAll(c | c.oclIsKindOf(Context) or c.oclIsKindOf(Assumption) or c.oclIsKindOf(Justification))"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicStrategy" eSuperTypes="#//Strategy"/>
  <eClassifiers xsi:type="ecore:EClass" name="ASILDecompositionStrategy" eSuperTypes="#//Strategy">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ASILDecompositionIndependence ASILDecompositionComponents ASILDescendants"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ASILDecompositionIndependence" value="&#xA;&#x9;&#x9;&#x9;let children = self.supportedBy.target -> closure(s | if s.oclIsKindOf(SupportConnector) then s.oclAsType(SupportConnector).supportedBy.target else s.oclAsSet() endif)&#xA;&#x9;&#x9;&#x9;in children -> selectByType(IndependenceGoal) -> size() = 1"/>
      <details key="ASILDecompositionComponents" value=" &#xA;&#x9;&#x9;&#x9;let children = self.supportedBy.target -> closure(s | if s.oclIsKindOf(SupportConnector) then s.oclAsType(SupportConnector).supportedBy.target else s.oclAsSet() endif)&#xA;&#x9;&#x9;&#x9;in children -> selectByType(BasicGoal) -> size() = 2"/>
      <details key="ASILDescendants" value="&#xA;&#x9;&#x9;&#x9;let goalSeq = self.supportedBy.target -> closure(s | if s.oclIsKindOf(SupportConnector) then s.oclAsType(SupportConnector).supportedBy.target else s.oclAsSet() endif) -> select(p | p.oclIsTypeOf(BasicGoal)), &#xA;&#x9;&#x9;&#x9;g1Descendants : Set(Supporter) = goalSeq -> at(1) -> closure(c | &#xA;&#x9;&#x9;&#x9;&#x9;&#x9;if c.oclIsKindOf(Supportable) then c.oclAsType(Supportable).supportedBy.target else null endif),&#xA;&#x9;&#x9;&#x9;g2Descendants : Set(Supporter) = goalSeq -> at(2) -> closure(c | &#xA;&#x9;&#x9;&#x9;&#x9;&#x9;if c.oclIsKindOf(Supportable) then c.oclAsType(Supportable).supportedBy.target else null endif) &#xA;&#x9;&#x9;&#x9;in g1Descendants -> intersection(g2Descendants) = Set{}"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Solution" eSuperTypes="#//CoreElement #//StatefulElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="SolutionSupporter SolutionContext"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="SolutionSupporter" value="self.oclAsType(DecomposableCoreElement).oclIsInvalid()"/>
      <details key="SolutionContext" value="self.oclAsType(DecomposableCoreElement).oclIsInvalid()"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Context" eSuperTypes="#//ContextualElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Justification" eSuperTypes="#//ContextualElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Assumption" eSuperTypes="#//ContextualElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ASIL">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="#//ASILLevel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//ASILfulElement" eOpposite="#//ASILfulElement/asil"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="status" eType="#//ImpactAnnotation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ASILLevel">
    <eLiterals name="D" literal="D"/>
    <eLiterals name="C" value="1" literal="C"/>
    <eLiterals name="B" value="2" literal="B"/>
    <eLiterals name="A" value="3" literal="A"/>
    <eLiterals name="QM" value="4" literal="QM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ValidityValue">
    <eLiterals name="Invalid" literal="Invalid"/>
    <eLiterals name="Valid" value="1" literal="Valid"/>
    <eLiterals name="Undetermined" value="2" literal="Undetermined"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ImpactType">
    <eLiterals name="Revise" value="1"/>
    <eLiterals name="RecheckContent" value="2" literal="RecheckContent"/>
    <eLiterals name="RecheckState" value="3" literal="RecheckState"/>
    <eLiterals name="Reuse" value="4" literal="Reuse"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImpactAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//ImpactType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Supportable" abstract="true" eSuperTypes="#//Supporter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="SupportCycle NonSupportableLeaves"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="SupportCycle" value="self.supportedBy.target -> closure(p | if p.oclIsKindOf(Supportable) then &#xA;&#x9;&#x9;&#x9;p.oclAsType(Supportable).supportedBy.target else &#xA;&#x9;&#x9;&#x9;p.oclAsSet() endif) -> excludes(self)"/>
      <details key="NonSupportableLeaves" value="self.supportedBy.target -> size() > 0 and self.supportedBy.target -> excludes(null)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedBy" lowerBound="1"
        upperBound="-1" eType="#//SupportedBy" containment="true" eOpposite="#//SupportedBy/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Supporter" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="GoalRoot"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="GoalRoot" value="self.supports.source -> isEmpty() implies self.oclIsTypeOf(BasicGoal)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supports" upperBound="-1"
        eType="#//SupportedBy" eOpposite="#//SupportedBy/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SupportConnector" abstract="true" eSuperTypes="#//Supportable"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndSupporter" eSuperTypes="#//SupportConnector"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrSupporter" eSuperTypes="#//SupportConnector"/>
  <eClassifiers xsi:type="ecore:EClass" name="XorSupporter" eSuperTypes="#//SupportConnector"/>
  <eClassifiers xsi:type="ecore:EClass" name="MofNSupporter" eSuperTypes="#//SupportConnector">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong" defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DecompositionStrategy" abstract="true"
      eSuperTypes="#//Strategy">
    <eOperations name="validate" eExceptions="#//Exception"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Domain" abstract="true">
    <eOperations name="validateDecomposition" eExceptions="#//Exception">
      <eParameters name="subDomains" upperBound="-1" eType="#//Domain"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntDomain" eSuperTypes="#//Domain">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RealDomain" eSuperTypes="#//Domain">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumDomain" eSuperTypes="#//Domain">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" lowerBound="2"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueDomain" eSuperTypes="#//Domain">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainDecompositionElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="domain" lowerBound="1"
        eType="#//Domain" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainDecompositionStrategy" eSuperTypes="#//DecompositionStrategy #//DomainDecompositionElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainGoal" eSuperTypes="#//Goal #//DomainDecompositionElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyDecompositionElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reasonerName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="property" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyDecompositionStrategy" eSuperTypes="#//DecompositionStrategy #//PropertyDecompositionElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyGoal" eSuperTypes="#//Goal #//PropertyDecompositionElement"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Exception" instanceClassName="java.lang.Exception"/>
</ecore:EPackage>
