<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gsn" nsURI="http://se.cs.toronto.edu/modelepedia/GSN" nsPrefix="gsn">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="SafetyCase">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="SingleGoalRoot"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="SingleGoalRoot" value="let root : Set(OclAny) = Supporter.allInstances()->select(s | s.supports->isEmpty()) in&#xA;  root->size() = 1 and root->forAll(g | g.oclIsKindOf(gsn::Goal))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="goals" upperBound="-1"
        eType="#//Goal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="strategies" upperBound="-1"
        eType="#//Strategy" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="solutions" upperBound="-1"
        eType="#//Solution" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contexts" upperBound="-1"
        eType="#//Context" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="justifications" upperBound="-1"
        eType="#//Justification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assumptions" upperBound="-1"
        eType="#//Assumption" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="templates" upperBound="-1"
        eType="#//Template" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArgumentElement" abstract="true">
    <eOperations name="validate" eExceptions="#//Exception"/>
    <eOperations name="instantiate" eExceptions="#//Exception"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="gmf.label">
        <details key="label" value="description"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="status" eType="#//ImpactAnnotation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="templates" upperBound="-1"
        eType="#//Template" eOpposite="#//Template/elements"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Decoratable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="decorators" upperBound="-1"
        eType="#//RelationshipDecorator" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Supportable" abstract="true" eSuperTypes="#//ArgumentElement #//Decoratable">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="SupportCycle StrategySupportsGoals"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="SupportCycle" value="self.supportedBy.target->closure(p | if p.oclIsKindOf(Supportable) then p.oclAsType(Supportable).supportedBy.target else p.oclAsSet() endif)->excludes(self)"/>
      <details key="StrategySupportsGoals" value="if self.oclIsKindOf(gsn::Strategy) then self.supportedBy->forAll(sb | sb.target.oclIsKindOf(gsn::Goal)) else true endif"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedBy" lowerBound="1"
        upperBound="-1" eType="#//SupportedBy" containment="true" eOpposite="#//SupportedBy/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="undeveloped" eType="#//Undeveloped"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Supporter" abstract="true" eSuperTypes="#//ArgumentElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="supports" upperBound="-1"
        eType="#//SupportedBy" eOpposite="#//SupportedBy/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SupportedBy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Supportable" eOpposite="#//Supportable/supportedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Supporter" eOpposite="#//Supporter/supports"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contextualizable" abstract="true" eSuperTypes="#//ArgumentElement #//Decoratable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inContextOf" upperBound="-1"
        eType="#//InContextOf" containment="true" eOpposite="#//InContextOf/contextOf"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contextual" abstract="true" eSuperTypes="#//ArgumentElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextOf" lowerBound="1"
        upperBound="-1" eType="#//InContextOf" eOpposite="#//InContextOf/context"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InContextOf">
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
        eType="#//Contextual" eOpposite="#//Contextual/contextOf"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextOf" lowerBound="1"
        eType="#//Contextualizable" eOpposite="#//Contextualizable/inContextOf"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASILfulElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="asil" eType="#//ASIL" containment="true"
        eOpposite="#//ASIL/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Goal" eSuperTypes="#//Supportable #//Supporter #//Contextualizable #//ASILfulElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ASILInheritance"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ASILInheritance" value="let parents : Set(Goal) = self.supports.source -> closure(c | if c.oclIsKindOf(Goal) then c.oclAsSet() else c.oclAsType(gsn::Supporter).supports.source endif) -> selectByKind(Goal) -> asSet() in&#xA;  parents -> forAll(g | if g.asil = null then true else if self.asil = null then false else g.asil.value = ASILLevel::QM or (g.asil.value.toString() &lt;= self.asil.value.toString() and self.asil.value &lt;> ASILLevel::QM) endif endif)"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Strategy" eSuperTypes="#//Supportable #//Supporter #//Contextualizable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Solution" eSuperTypes="#//Supporter"/>
  <eClassifiers xsi:type="ecore:EClass" name="Context" eSuperTypes="#//Contextual"/>
  <eClassifiers xsi:type="ecore:EClass" name="Justification" eSuperTypes="#//Contextual"/>
  <eClassifiers xsi:type="ecore:EClass" name="Assumption" eSuperTypes="#//Contextual"/>
  <eClassifiers xsi:type="ecore:EClass" name="Undeveloped"/>
  <eClassifiers xsi:type="ecore:EClass" name="ASIL">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="#//ASILLevel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//ASILfulElement" eOpposite="#//ASILfulElement/asil"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="status" eType="#//ImpactAnnotation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ASILLevel">
    <eLiterals name="D" literal="D"/>
    <eLiterals name="C" value="1" literal="C"/>
    <eLiterals name="B" value="2" literal="B"/>
    <eLiterals name="A" value="3" literal="A"/>
    <eLiterals name="QM" value="4" literal="QM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImpactAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//ImpactType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ImpactType">
    <eLiterals name="Revise" value="1"/>
    <eLiterals name="RecheckContent" value="2" literal="RecheckContent"/>
    <eLiterals name="RecheckState" value="3" literal="RecheckState"/>
    <eLiterals name="Reuse" value="4" literal="Reuse"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Template">
    <eOperations name="validate" eExceptions="#//Exception"/>
    <eOperations name="import_" lowerBound="1" eExceptions="#//Exception">
      <eParameters name="safetyCase" lowerBound="1" eType="#//SafetyCase"/>
    </eOperations>
    <eOperations name="instantiate" eExceptions="#//Exception"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" lowerBound="1"
        upperBound="-1" eType="#//ArgumentElement" eOpposite="#//ArgumentElement/templates"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipDecorator" eSuperTypes="#//Supportable #//Contextualizable">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="OneRelationship"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="OneRelationship" value="self.supportedBy->isEmpty() or self.inContextOf->isEmpty()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//DecoratorType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinality" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DecoratorType">
    <eLiterals name="MULTIPLE"/>
    <eLiterals name="OPTIONAL" value="1"/>
    <eLiterals name="CHOICE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Exception" instanceClassName="java.lang.Exception"/>
  <eClassifiers xsi:type="ecore:EDataType" name="GSNBuilder" instanceClassName="edu.toronto.cs.se.modelepedia.gsn.util.GSNBuilder"/>
</ecore:EPackage>
