<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="productline" nsURI="model://edu.toronto.cs.se.mmint.types.gsn.productline"
    nsPrefix="gsn.productline">
  <eClassifiers xsi:type="ecore:EClass" name="PLGSNArgumentElement" eSuperTypes="../../edu.toronto.cs.se.mmint.productline/model/productline.ecore#//Class">
    <eOperations name="instantiate" eExceptions="ecore:EDataType ../../edu.toronto.cs.se.modelepedia.gsn/model/gsn.ecore#//Exception"/>
    <eOperations name="validate" eExceptions="ecore:EDataType ../../edu.toronto.cs.se.modelepedia.gsn/model/gsn.ecore#//Exception"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PLGSNTemplate" eSuperTypes="../../edu.toronto.cs.se.mmint.productline/model/productline.ecore#//Class">
    <eOperations name="getElementsById" lowerBound="1">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eTypeArguments eClassifier="#//PLGSNArgumentElement"/>
      </eGenericType>
    </eOperations>
    <eOperations name="import_" eExceptions="ecore:EDataType ../../edu.toronto.cs.se.modelepedia.gsn/model/gsn.ecore#//Exception">
      <eParameters name="productLine" lowerBound="1" eType="ecore:EClass ../../edu.toronto.cs.se.mmint.productline/model/productline.ecore#//ProductLine"/>
    </eOperations>
    <eOperations name="instantiate" eExceptions="ecore:EDataType ../../edu.toronto.cs.se.modelepedia.gsn/model/gsn.ecore#//Exception"/>
    <eOperations name="validate" eExceptions="ecore:EDataType ../../edu.toronto.cs.se.modelepedia.gsn/model/gsn.ecore#//Exception"/>
    <eOperations name="impact" upperBound="-1" eType="#//PLGSNImpactStep" eExceptions="ecore:EDataType ../../edu.toronto.cs.se.modelepedia.gsn/model/gsn.ecore#//Exception">
      <eParameters name="step" lowerBound="1" eType="#//PLGSNImpactStep"/>
      <eParameters name="change" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="repair" eExceptions="ecore:EDataType ../../edu.toronto.cs.se.modelepedia.gsn/model/gsn.ecore#//Exception">
      <eParameters name="change" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PLGSNAnalyticTemplate" eSuperTypes="#//PLGSNTemplate">
    <eOperations name="getAnalysis" eType="#//IPLGSNAnalysis" eExceptions="ecore:EDataType ../../edu.toronto.cs.se.modelepedia.gsn/model/gsn.ecore#//Exception"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IPLGSNAnalysis" instanceClassName="edu.toronto.cs.se.mmint.types.gsn.productline.reasoning.IPLGSNAnalysis"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PLGSNImpactStep" instanceClassName="edu.toronto.cs.se.mmint.types.gsn.productline.util.PLGSNImpactStep"/>
</ecore:EPackage>
