<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="productline" nsURI="model://edu.toronto.cs.se.mmint.types.gsn.productline"
    nsPrefix="gsn.productline">
  <eClassifiers xsi:type="ecore:EClass" name="GSNPLArgumentElement" eSuperTypes="../../edu.toronto.cs.se.mmint.productline/model/productline.ecore#//Class">
    <eOperations name="validate" eExceptions="ecore:EDataType ../../edu.toronto.cs.se.modelepedia.gsn/model/gsn.ecore#//Exception">
      <eParameters name="template" eType="#//GSNPLTemplate"/>
    </eOperations>
    <eOperations name="instantiate" eExceptions="ecore:EDataType ../../edu.toronto.cs.se.modelepedia.gsn/model/gsn.ecore#//Exception">
      <eParameters name="template" eType="#//GSNPLTemplate"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSNPLTemplate" eSuperTypes="../../edu.toronto.cs.se.mmint.productline/model/productline.ecore#//Class">
    <eOperations name="validate" eExceptions="ecore:EDataType ../../edu.toronto.cs.se.modelepedia.gsn/model/gsn.ecore#//Exception"/>
    <eOperations name="import_" eExceptions="ecore:EDataType ../../edu.toronto.cs.se.modelepedia.gsn/model/gsn.ecore#//Exception">
      <eParameters name="productLine" lowerBound="1" eType="ecore:EClass ../../edu.toronto.cs.se.mmint.productline/model/productline.ecore#//ProductLine"/>
    </eOperations>
    <eOperations name="instantiate" eExceptions="ecore:EDataType ../../edu.toronto.cs.se.modelepedia.gsn/model/gsn.ecore#//Exception"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GSNPLAnalysisTemplate" eSuperTypes="#//GSNPLTemplate">
    <eOperations name="getRunner" eType="#//IGSNPLAnalysisRunner" eExceptions="ecore:EDataType ../../edu.toronto.cs.se.modelepedia.gsn/model/gsn.ecore#//Exception"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IGSNPLAnalysisRunner" instanceClassName="edu.toronto.cs.se.mmint.types.gsn.productline.reasoning.IGSNPLAnalysisRunner"/>
</ecore:EPackage>
