<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="GPL" nsURI="https://gpl.org" nsPrefix="gpl">
  <eAnnotations source="features">
    <details key="file" value="model.xml"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeIfc">
    <eAnnotations source="presence">
      <details key="condition" value="Base or WeightedOnlyVertices or WeightedWithEdges or WeightedWithNeighbors"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeIter">
    <eAnnotations source="presence">
      <details key="condition" value="Base"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NeighborIfc">
    <eAnnotations source="presence">
      <details key="condition" value="Base"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VertexIter">
    <eAnnotations source="presence">
      <details key="condition" value="Base"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vertex">
    <eAnnotations source="presence">
      <details key="condition" value="BFS or Connected or Cycle or DFS or DirectedWithEdges or DirectedWithNeighbors or MSTKruskal or MSTPrim or Number or StronglyConnected or UndirectedOnlyVertices or UndirectedWithEdges or UndirectedWithNeighbors or WeightedOnlyVertices or WeightedWithNeighbors"/>
    </eAnnotations>
    <eAnnotations source="presence">
      <details key="condition" value="Cycle"/>
      <details key="constraint" value="validColor"/>
    </eAnnotations>
    <eAnnotations source="modifier">
      <details key="condition" value="DirectedOnlyVertices or UndirectedOnlyVertices"/>
      <details key="extend" value="EdgeIfc NeighborIfc"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="validColor"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="validColor" value="self.VertexColor = 0 or self.VertexColor = 1 or self.VertexColor = 2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visited" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="presence">
        <details key="condition" value="BFS or DFS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="componentNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="presence">
        <details key="condition" value="Connected"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VertexCycle" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="presence">
        <details key="condition" value="Cycle"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VertexColor" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="presence">
        <details key="condition" value="Cycle"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adjacentVertices" ordered="false"
        upperBound="-1" eType="#//Vertex">
      <eAnnotations source="presence">
        <details key="condition" value="DirectedOnlyVertices or UndirectedOnlyVertices"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="presence">
        <details key="condition" value="DirectedOnlyVertices or DirectedWithEdges or DirectedWithNeighbors or UndirectedOnlyVertices or UndirectedWithEdges or UndirectedWithNeighbors"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="neighbors" ordered="false"
        upperBound="-1" eType="#//Neighbor">
      <eAnnotations source="presence">
        <details key="condition" value="DirectedWithEdges or UndirectedWithEdges"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adjacentNeighbors" ordered="false"
        upperBound="-1" eType="#//Neighbor">
      <eAnnotations source="presence">
        <details key="condition" value="DirectedWithNeighbors or UndirectedWithNeighbors"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="representative" eType="#//Vertex">
      <eAnnotations source="presence">
        <details key="condition" value="MSTKruskal"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" ordered="false"
        upperBound="-1" eType="#//Vertex">
      <eAnnotations source="presence">
        <details key="condition" value="MSTKruskal"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pred" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="presence">
        <details key="condition" value="MSTPrim"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="akey" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="presence">
        <details key="condition" value="MSTPrim"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VertexNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="presence">
        <details key="condition" value="Number"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="finishTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="presence">
        <details key="condition" value="StronglyConnected"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strongComponentNumber"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="presence">
        <details key="condition" value="StronglyConnected"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weightsList" ordered="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="presence">
        <details key="condition" value="WeightedOnlyVertices"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Graph">
    <eAnnotations source="presence">
      <details key="condition" value="BFS or Connected or Cycle or DFS or DirectedOnlyVertices or DirectedWithEdges or DirectedWithNeighbors or MSTKruskal or MSTPrim or Number or StronglyConnected or Transpose or UndirectedOnlyVertices or UndirectedWithEdges or UndirectedWithNeighbors or WeightedOnlyVertices or WeightedWithNeighbors"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vertices" ordered="false"
        upperBound="-1" eType="#//Vertex">
      <eAnnotations source="presence">
        <details key="condition" value="DirectedOnlyVertices or DirectedWithEdges or DirectedWithNeighbors or UndirectedOnlyVertices or UndirectedWithEdges or UndirectedWithNeighbors"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDirected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="presence">
        <details key="condition" value="DirectedOnlyVertices or DirectedWithEdges or DirectedWithNeighbors or UndirectedOnlyVertices or UndirectedWithEdges or UndirectedWithNeighbors"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" ordered="false"
        upperBound="-1" eType="#//Edge">
      <eAnnotations source="presence">
        <details key="condition" value="DirectedWithEdges or UndirectedWithEdges"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GlobalVarsWrapper">
    <eAnnotations source="presence">
      <details key="condition" value="BFS"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkSpace">
    <eAnnotations source="presence">
      <details key="condition" value="BFS or DFS"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegionWorkSpace" eSuperTypes="#//WorkSpace">
    <eAnnotations source="presence">
      <details key="condition" value="Connected"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="counterValue"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="counterValue" value="self.counter >= 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="counter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CycleWorkSpace">
    <eAnnotations source="presence">
      <details key="condition" value="Cycle"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="colorValues"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="colorValues" value="self.WHITE = 0 and self.GRAY = 1 and self.BLACK = 2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AnyCycles" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDirected" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vertices" ordered="false"
        upperBound="-1" eType="#//Vertex">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="WHITE" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GRAY" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BLACK" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Neighbor">
    <eAnnotations source="presence">
      <details key="condition" value="DirectedWithEdges or DirectedWithNeighbors or UndirectedWithEdges or UndirectedWithNeighbors or WeightedWithNeighbors"/>
    </eAnnotations>
    <eAnnotations source="modifier">
      <details key="condition" value="DirectedWithNeighbors or UndirectedWithNeighbors"/>
      <details key="extend" value="EdgeIfc NeighborIfc"/>
    </eAnnotations>
    <eAnnotations source="modifier">
      <details key="condition" value="UndirectedWithEdges"/>
      <details key="extend" value="NeighborIfc"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" eType="#//Vertex">
      <eAnnotations source="presence">
        <details key="condition" value="DirectedWithEdges or UndirectedWithEdges"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edge" eType="#//Edge">
      <eAnnotations source="presence">
        <details key="condition" value="DirectedWithEdges or UndirectedWithEdges"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="neighbor" eType="#//Vertex">
      <eAnnotations source="presence">
        <details key="condition" value="DirectedWithNeighbors or UndirectedWithNeighbors"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="presence">
        <details key="condition" value="WeightedWithNeighbors"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edge" eSuperTypes="#//Neighbor #//EdgeIfc">
    <eAnnotations source="presence">
      <details key="condition" value="DirectedWithEdges or UndirectedWithEdges or WeightedWithEdges"/>
    </eAnnotations>
    <eAnnotations source="modifier">
      <details key="condition" value="WeightedWithEdges"/>
      <details key="reduce" value="Neighbor EdgeIfc"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//Vertex">
      <eAnnotations source="presence">
        <details key="condition" value="DirectedWithEdges or UndirectedWithEdges"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight2" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="presence">
        <details key="condition" value="WeightedWithEdges"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberWorkSpace" eSuperTypes="#//WorkSpace">
    <eAnnotations source="presence">
      <details key="condition" value="Number"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="counterValue"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="counterValue" value="self.vertexCounter >= 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vertexCounter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FinishTimeWorkSpace" eSuperTypes="#//WorkSpace">
    <eAnnotations source="presence">
      <details key="condition" value="StronglyConnected"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="counterValue"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="counterValue" value="self.FinishCounter > 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FinishCounter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkSpaceTranspose" eSuperTypes="#//WorkSpace">
    <eAnnotations source="presence">
      <details key="condition" value="StronglyConnected"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="counterValue"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="counterValue" value="self.SCCCounter >= 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SCCCounter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Main">
    <eAnnotations source="presence">
      <details key="condition" value="TestProg"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="g" lowerBound="1" eType="#//Graph"/>
  </eClassifiers>
</ecore:EPackage>
