<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="PetriNets" nsURI="http://www.petrinets.org/" nsPrefix="ex">
  <eAnnotations source="features">
    <details key="file" value="model.xml"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="PetriNet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="places" ordered="false"
        upperBound="-1" eType="#//Place" containment="true" eOpposite="#//Place/net"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trans" ordered="false"
        upperBound="-1" eType="#//Transition" containment="true" eOpposite="#//Transition/net"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Place">
    <eAnnotations source="presence">
      <details key="condition" value="MarkedGraph"/>
      <details key="constraint" value="isMarkedGraph"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="isMarkedGraph"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="isMarkedGraph" value="&#xA;&#x9;&#x9;&#x9;Transition.allInstances()->one(ins->includes(self)) and&#xA;&#x9;&#x9;&#x9;Transition.allInstances()->one(outs->includes(self))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="itokens" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="presence">
        <details key="condition" value="Simple"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="net" lowerBound="1" eType="#//PetriNet"
        eOpposite="#//PetriNet/places"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tokens" ordered="false"
        upperBound="-1" eType="#//Token" containment="true" eOpposite="#//Token/place">
      <eAnnotations source="presence">
        <details key="condition" value="Object"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Token">
    <eAnnotations source="presence">
      <details key="condition" value="Object"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="place" lowerBound="1" eType="#//Place"
        eOpposite="#//Place/tokens"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#//PetriNet">
    <eAnnotations source="presence">
      <details key="condition" value="Hierarchical"/>
      <details key="constraint" value="isHierarchical"/>
    </eAnnotations>
    <eAnnotations source="modifier">
      <details key="reduce" value="PetriNet"/>
      <details key="condition" value="not Hierarchical"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="isHierarchical"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="isHierarchical" value="&#xA;&#x9;&#x9;&#x9;(places->size()>0 or trans->size()>0) &#xA;&#x9;&#x9;&#x9;implies &#xA;&#x9;&#x9;&#x9;(ins->size()=0 and outs->size()=0)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="net" lowerBound="1" eType="#//PetriNet"
        eOpposite="#//PetriNet/trans"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ins" ordered="false" upperBound="-1"
        eType="#//Place">
      <eAnnotations source="modifier">
        <details key="condition" value="StateMachine"/>
        <details key="min" value="1"/>
        <details key="max" value="1"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outs" ordered="false" upperBound="-1"
        eType="#//Place">
      <eAnnotations source="modifier">
        <details key="condition" value="StateMachine"/>
        <details key="min" value="1"/>
        <details key="max" value="1"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
